### PR TITLE
GET endpoint for items by category

### PR DESCRIPTION
**Pull request by sam-h-hall**
added getItemsByCategoryID to globalModels in order to query db for items matching specified category. Added route to itemsRouter to search for items belonging to a category.

### CODE REVIEW

**Review by Brodt7258 — DISMISSED** [review]
looks good, that was very easy to follow.

**Review by karapeoples — COMMENTED** [review]
Can you make  api/items/itemsRouter.js line 43  if statement with an explicit === instead of the == just to prevent future errors then you should be good

**Comment by sam-h-hall** [comment]
> Can you make api/items/itemsRouter.js line 43 if statement with an explicit === instead of the == just to prevent future errors then you should be good

Great catch, I added a commit to fix it.

**Review by jonathan-portillo — APPROVED** [review]
Very straight forward! Looks good to me!

**Review by karapeoples — APPROVED** [review]
Everything looks perfectly in order now

**Pull request merged**
